### ISSUE TITLE
US2.1.2 - Can migrate and seed

### ISSUE THREAD

**Issue by Frequencerz911** [WildCodeSchool-2023-09/JS-RemoteFR-jurascripts-P3-Originsdigital#19]
- [x] migrate
- [x] seed

- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25 
- [x] #26
- [x] #27

**Comment by Cal-y** [comment]
Make table : 

- [ ] #20 
- [ ] #21
- [ ] #22

**Comment by Tetardtek** [comment]
Do it together 20/12/2023
